PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tosl: <https://w3id.org/tosl/>

SELECT DISTINCT ?duty ?action ?target ?assignee
WHERE {
  ?duty a odrl:Duty .
  ?duty odrl:action ?action .
  ?duty odrl:target ?target .
  ?duty odrl:assignee ?assignee .
}
