PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX tosl: <http://www.w3.org/tosl/>

SELECT ?duty ?action ?assignee ?target
WHERE {
    ?duty a odrl:Duty ;
          odrl:action ?action ;
          odrl:assignee ?assignee ;
          odrl:target ?target ;
          odrl:constraint ?constraint .

    ?constraint odrl:rightOperand tosl:implicitConsent .

    FILTER (?action = tosl:consent && ?assignee = :customer01)
}