PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tosl: <http://www.w3.org/tosl/>

SELECT DISTINCT ?limitationOn ?liability ?type ?liableParty
WHERE {
  ?liability a tosl:Liability ;
    tosl:liableParty ?liableParty ;
    rdf:value ?type .
  
  ?limitationOn tosl:limitationOfLiability ?liability .
  
  FILTER (?liableParty = :elsevier)

  FILTER (?type = tosl:anyLiability || ?type = tosl:physicalInjuries || ?type = tosl:harmCausedByMalware )
}