PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tosl: <https://w3id.org/tosl/>

SELECT DISTINCT ?dispute ?place
WHERE {
  ?dispute tosl:onDispute ?litigation .
  ?litigation a tosl:Litigation ;
              tosl:takesPlaceIn ?place .

  ?place a tosl:Jurisdiction .

  FILTER NOT EXISTS {
    ?dispute tosl:onDispute ?litigation2 .
    ?litigation2 tosl:takesPlaceIn tosl:consumerPlaceCourts .
  }
}
