PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tosl: <https://w3id.org/tosl/>

SELECT ?prohibition (GROUP_CONCAT(?action; separator=", ") AS ?actions) ?target ?assignee
WHERE {
    ?prohibition a odrl:Prohibition .
    ?prohibition odrl:action ?action .
    ?prohibition odrl:target ?target .
    ?prohibition odrl:assignee ?assignee .
    ?assignee a tosl:Customer .
}
GROUP BY ?prohibition ?target ?assignee
