PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tosl: <https://w3id.org/tosl/>

SELECT DISTINCT ?limitationOn ?liability ?type ?liableParty
WHERE {
  ?liability a tosl:Liability ;
    tosl:liableParty ?liableParty ;
    rdf:value ?type .
  
  ?liableParty a tosl:Provider .
  
  {
    ?limitationOn tosl:limitationOfLiability ?liability .
  } UNION {
    ?limitationOn tosl:liability ?liability .
    ?liability odrl:limitation ?constraint .  
  }

  FILTER (?type = tosl:anyLiability || ?type = tosl:physicalInjuries || ?type = tosl:harmCausedByMalware )
}