PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tosl: <http://www.w3.org/tosl/>

SELECT ?permission ?action ?target
WHERE {
    ?permission a odrl:Permission ;
        odrl:action ?action ;
        odrl:target ?target .
    FILTER NOT EXISTS {
        ?permission odrl:constraint ?constraint .
    }
    FILTER NOT EXITS {
        ?permission odrl:duty ?duty .
    }
    FILTER (?action = odrl:modify)
}