PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tosl: <http://www.w3.org/tosl/>

SELECT ?permission ?action ?assignee ?target
WHERE {
    ?permission a odrl:Permission ;
        odrl:action ?action ;
        odrl:assignee ?assignee ;
        odrl:target ?target .
    FILTER NOT EXISTS {
        ?permission odrl:constraint ?constraint .
    }
    FILTER NOT EXISTS {
        ?permission odrl:duty ?duty .
    }
    FILTER (?action = tosl:terminate ||
            ?action = tosl:suspend ||
            ?action = tosl:remove ||
            ?action = tosl:disable)
}